simple_shell: simple_shell.o
	gcc -o simple_shell simple_shell.o
simple_shell.o: simple_shell.c
	gcc -c simple_shell.c
clean:
	rm simple_shell simple_shell.o

#  -c Compile or assemble the source files, but do not link.
#  The ultimate output is in the form of an object file for each source file. 

# -o file Place the primary output in file file. 

# targets: prerequisites
# The targets are file names

# make clean will run clean  