multithreaded_sort: multithreaded_sort.o
	gcc -pthread -o multithreaded_sort multithreaded_sort.o
multithreaded_sort.o: multithreaded_sort.c
	gcc -c multithreaded_sort.c
clean:
	rm multithreaded_sort multithreaded_sort.o
